# Generated by Django 5.0.1 on 2024-02-12 10:05

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_caption_blogpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='category',
            field=wagtail.fields.StreamField([('category', wagtail.blocks.ChoiceBlock(choices=[('happyfox-help-desk', 'HappyFox Help Desk'), ('happyfox-service-desk', 'HappyFox Service Desk'), ('happyfox-bi', 'HappyFox BI'), ('happyfox-chatbot', 'HappyFox ChatBot'), ('miscellaneous', 'Miscellaneous')]))], blank=True),
        ),
    ]
